import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "1.5rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        display: ['"Anton"', '"Bebas Neue"', "Impact", "sans-serif"],
        impact: ['"Bebas Neue"', '"Anton"', "Impact", "sans-serif"],
        condensed: ['"Oswald"', '"Teko"', "Impact", "sans-serif"],
        athletic: ['"Teko"', '"Rajdhani"', "sans-serif"],
        tech: ['"Rajdhani"', '"Teko"', "sans-serif"],
        cyber: ['"Orbitron"', '"Rajdhani"', "sans-serif"],
        sans: ['"Inter"', '"Poppins"', "system-ui", "sans-serif"],
        body: ['"Inter"', '"Poppins"', "system-ui", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
        },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        carbon: { DEFAULT: "hsl(var(--carbon))", light: "hsl(var(--carbon-light))" },
        ember: "hsl(var(--ember))",
      },
      backgroundImage: {
        fire: "var(--gradient-fire)",
        "fire-soft": "var(--gradient-fire-soft)",
        "dark-grad": "var(--gradient-dark)",
        "radial-glow": "var(--gradient-radial-glow)",
        overlay: "var(--gradient-overlay)",
      },
      boxShadow: {
        glow: "var(--shadow-glow)",
        "glow-strong": "var(--shadow-glow-strong)",
        card: "var(--shadow-card)",
      },
      borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)" },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "text-reveal": { "0%": { opacity: "0", transform: "translateY(40px) skewY(6deg)", filter: "blur(12px)" }, "100%": { opacity: "1", transform: "translateY(0) skewY(0)", filter: "blur(0)" } },
        "letter-spread": { "0%": { letterSpacing: "-0.05em", opacity: "0" }, "100%": { letterSpacing: "0.04em", opacity: "1" } },
        "shimmer": { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s var(--ease-combat, ease-out) both",
        "text-reveal": "text-reveal 0.9s var(--ease-combat, ease-out) both",
        "letter-spread": "letter-spread 1.2s var(--ease-combat, ease-out) both",
        "shimmer": "shimmer 4s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
